[package]
name = "packobf_gui"
version = "0.2.1"
edition = "2024"
license = "MIT"

[dependencies]
imgui = "0.12"
imgui-glow-renderer = "0.13"
imgui-winit-support = "0.13"

glow = "0.14"

glutin = "0.32"
glutin-winit = "0.5"
winit = { version = "0.30", features = ["rwh_06"] }
raw-window-handle = "0.6"

tokio = { version = "1.50" }

rfd = "0.15"

arboard = "3"

packobf = { path = "../packobf" }

[features]
default = []
profiling = ["packobf/profiling"]
