use crate::options::{Compression, PreCheckResult};
use crate::{options, profile_scope, LogLevel, LogMessage};
use byteorder::{BigEndian, WriteBytesExt};
use libdeflater::{crc32, CompressionLvl, Decompressor};
use std::io::{Error, Write};
use tokio::sync::mpsc::UnboundedSender;
use zopfli::{Options, ZlibEncoder};

/// [PNG Specification, version 3.0](https://www.w3.org/TR/png-3/)
///
/// Re-compresses deflate idat using zopfli with dynamic options
/// See [options::analyze](options::analyze).
/// The input is only meant to be generated by oxipng as it does
/// not fully support the format but what oxipng generates.
pub fn rewrite_idat_with_zopfli(
    input: &[u8],
    compression: &Compression,
    logger: &UnboundedSender<LogMessage>,
) -> Vec<u8> {
    profile_scope!(std::any::type_name_of_val(&rewrite_idat_with_zopfli));
    const PNG_SIGNATURE: [u8; 8] = [137, 80, 78, 71, 13, 10, 26, 10];

    if input.len() < 8 || input[0..8] != PNG_SIGNATURE {
        return input.into();
    }

    let mut output = Vec::with_capacity(input.len());
    output.extend_from_slice(&PNG_SIGNATURE);

    let mut offset = 8;

    let mut width = None;
    let mut height = None;
    let mut bit_depth = None;
    let mut color_type = None;
    let mut interlace_method = None;

    while offset < input.len() {
        if offset + 8 > input.len() {
            return input.into();
        }

        let length = u32::from_be_bytes([
            input[offset],
            input[offset + 1],
            input[offset + 2],
            input[offset + 3],
        ]) as usize;

        let chunk_type = &input[offset + 4..offset + 8];

        let chunk_end = offset + 8 + length;
        let crc_end = chunk_end + 4;
        if crc_end > input.len() {
            let _ = logger.send(LogMessage {
                level: LogLevel::Error,
                message: format!("CRC end is higher than input for chunk {}", String::from_utf8_lossy(chunk_type)),
            });
            return input.into();
        }

        // According to the spec, IHDR must be the first chunk so we don't need to parse them all first.
        if chunk_type == b"IHDR" {
            if length != 13 {
                let _ = logger.send(LogMessage {
                    level: LogLevel::Error,
                    message: format!("Wrong length for IHDR chunk: {}", length),
                });
                return input.into();
            }

            let data = &input[offset + 8..chunk_end];

            width = Some(u32::from_be_bytes([
                data[0], data[1], data[2], data[3],
            ]));

            height = Some(u32::from_be_bytes([
                data[4], data[5], data[6], data[7],
            ]));

            bit_depth = Some(data[8]);
            color_type = Some(data[9]);
            interlace_method = Some(data[12]);

            output.extend_from_slice(&input[offset..crc_end]);
        } else if chunk_type == b"IDAT" {
            let chunk_start = offset + 8;
            // See [zlib data format](https://en.wikipedia.org/wiki/Zlib#Data_format).
            // DICTID is not supported here, but it should never be used.
            let data = &input[
                chunk_start + 2 // removes the zlib header
                    ..
                    chunk_end - 4 // removes the zlib checksum
                ];

            let decompressed_size = calculate_decompressed_idat_size(
                width.unwrap_or(0),
                height.unwrap_or(0),
                bit_depth.unwrap_or(0),
                color_type.unwrap_or(0),
                interlace_method.unwrap_or(0),
            );
            let decompressed_size = match decompressed_size {
                None => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: "Failed to calculate decompressed size for PNG IDAT chunk using IHDR data".to_string(),
                    });
                    return input.into();
                }
                Some(x) => x
            };

            let mut original_data = vec![0u8; decompressed_size];
            match Decompressor::new().deflate_decompress(data, &mut original_data) {
                Ok(original_size) => {
                    original_data.truncate(original_size);
                    let data_size = data.len();
                    let bytes_saved = original_size.saturating_sub(data_size);
                    let savings_ratio = bytes_saved as f64 / original_size as f64;

                    match compression {
                        Compression::Normal => {
                            let result =
                                options::get_normal_precheck_result(savings_ratio, original_size);
                            compress_data_and_write_idat(
                                input,
                                logger,
                                &mut output,
                                original_data.as_slice(),
                                offset,
                                crc_end,
                                data_size,
                                result,
                            );
                        }
                        Compression::Best => {
                            let result =
                                options::get_best_pre_check_result(savings_ratio, original_size);
                            compress_data_and_write_idat(
                                input,
                                logger,
                                &mut output,
                                original_data.as_slice(),
                                offset,
                                crc_end,
                                data_size,
                                result,
                            );
                        }
                        compression => {
                            let _ = logger.send(LogMessage {
                                level: LogLevel::Error,
                                message: format!(
                                    "{} called with {:?}",
                                    std::any::type_name_of_val(&rewrite_idat_with_zopfli),
                                    compression
                                ),
                            });
                            return input.into();
                        }
                    }
                }
                Err(e) => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: format!("Failed to decompress PNG IDAT data: {:?}", e),
                    });
                    return input.into();
                }
            }
        } else {
            output.extend_from_slice(&input[offset..crc_end]);
        }

        offset = crc_end;
    }

    output
}

fn compress_data_and_write_idat(
    input: &[u8],
    logger: &UnboundedSender<LogMessage>,
    output: &mut Vec<u8>,
    original_data: &[u8],
    offset: usize,
    crc_end: usize,
    data_size: usize,
    result: PreCheckResult,
) {
    let out = match result {
        PreCheckResult::CompressWithZopfli(options) => match compress(original_data, options) {
            Ok(out) => out,
            Err(e) => {
                let _ = logger.send(LogMessage {
                    level: LogLevel::Error,
                    message: format!("Failed to compress PNG data with zopfli: {:?}", e),
                });
                output.extend_from_slice(&input[offset..crc_end]);
                return;
            }
        },
        PreCheckResult::LibDeflater => {
            let mut compressor = libdeflater::Compressor::new(CompressionLvl::best());
            let mut out = vec![0u8; compressor.zlib_compress_bound(data_size)];
            let size = match compressor.zlib_compress(original_data, &mut out) {
                Ok(out) => out,
                Err(e) => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: format!("Failed to compress PNG data with libdeflate: {:?}", e),
                    });
                    output.extend_from_slice(&input[offset..crc_end]);
                    return;
                }
            };
            out.truncate(size);
            out
        }
        PreCheckResult::Skip => {
            output.extend_from_slice(&input[offset..crc_end]);
            return;
        }
    };
    let out_size = out.len();
    if out_size > data_size + 6
    // Add 6 bytes for header and checksum
    {
        output.extend_from_slice(&input[offset..crc_end]);
        return;
    }
    match write_idat(output, out_size, out) {
        Ok(_) => {}
        Err(e) => {
            let _ = logger.send(LogMessage {
                level: LogLevel::Error,
                message: format!("Failed to write PNG IDAT: {:?}", e),
            });
            output.extend_from_slice(&input[offset..crc_end]);
        }
    }
}

fn write_idat(output: &mut Vec<u8>, out_size: usize, data: Vec<u8>) -> std::io::Result<()> {
    output.write_u32::<BigEndian>(out_size as u32)?;
    output.extend_from_slice(b"IDAT");
    output.extend_from_slice(data.as_slice());
    output.write_u32::<BigEndian>(crc32(&output[output.len() - out_size - b"IDAT".len()..]))?;
    Ok(())
}

fn compress(original_data: &[u8], options: Options) -> Result<Vec<u8>, Error> {
    let mut encoder = ZlibEncoder::new(options, zopfli::BlockType::Dynamic, Vec::new())?;
    encoder.write_all(original_data)?;
    let out = encoder.finish()?;
    Ok(out)
}

#[macro_export]
macro_rules! compress {
    ($options:expr) => {{}};
}

#[macro_export]
macro_rules! stop {
    ($output:expr, $input:expr, $offset:expr) => {{
        input
    }};
}

/// [11.2.1 IHDR Image header](https://www.w3.org/TR/png-3/#11IHDR)
pub fn calculate_decompressed_idat_size(
    width: u32,
    height: u32,
    bit_depth: u8,
    color_type_raw: u8,
    interlace_method: u8,
) -> Option<usize> {
    if width == 0 || height == 0 {
        return None;
    }

    let color_type = ColorType::from_u8(color_type_raw)?;

    // Validate bit depth and color type
    let valid_depth = match color_type {
        ColorType::Greyscale => matches!(bit_depth, 1 | 2 | 4 | 8 | 16),
        ColorType::Truecolor => matches!(bit_depth, 8 | 16),
        ColorType::Indexed => matches!(bit_depth, 1 | 2 | 4 | 8),
        ColorType::GreyscaleWithAlpha => matches!(bit_depth, 8 | 16),
        ColorType::TruecolorWithAlpha => matches!(bit_depth, 8 | 16),
    };

    if !valid_depth {
        return None;
    }

    let bits_per_pixel = (color_type.channels() * bit_depth as usize) as u64;

    match interlace_method {
        0 => {
            // Non-interlaced: Each row is packed to bytes + 1 filter byte
            let row_bytes = (width as u64 * bits_per_pixel + 7) / 8;
            let total_size = (height as u64) * (1 + row_bytes);
            usize::try_from(total_size).ok()
        }
        1 => {
            // Adam7 Interlace: 7 passes
            const START_ROW: [u32; 7] = [0, 0, 4, 0, 2, 0, 1];
            const START_COL: [u32; 7] = [0, 4, 0, 2, 0, 1, 0];
            const ROW_INC: [u32; 7]   = [8, 8, 8, 4, 4, 2, 2];
            const COL_INC: [u32; 7]   = [8, 8, 4, 4, 2, 2, 1];

            let mut total_size: u64 = 0;

            for pass in 0..7 {
                let pass_width = if width > START_COL[pass] {
                    ((width - 1 - START_COL[pass]) / COL_INC[pass] + 1) as u64
                } else {
                    0
                };

                let pass_height = if height > START_ROW[pass] {
                    ((height - 1 - START_ROW[pass]) / ROW_INC[pass] + 1) as u64
                } else {
                    0
                };

                if pass_width > 0 && pass_height > 0 {
                    let row_bytes = (pass_width * bits_per_pixel + 7) / 8;
                    total_size += pass_height * (1 + row_bytes);
                }
            }

            usize::try_from(total_size).ok()
        }
        _ => None, // Unrecognized interlace method
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ColorType {
    Greyscale = 0,
    Truecolor = 2,
    Indexed = 3,
    GreyscaleWithAlpha = 4,
    TruecolorWithAlpha = 6,
}

impl ColorType {
    pub fn from_u8(val: u8) -> Option<Self> {
        match val {
            0 => Some(ColorType::Greyscale),
            2 => Some(ColorType::Truecolor),
            3 => Some(ColorType::Indexed),
            4 => Some(ColorType::GreyscaleWithAlpha),
            6 => Some(ColorType::TruecolorWithAlpha),
            _ => None,
        }
    }

    /// Number of channels/samples per pixel
    pub fn channels(self) -> usize {
        match self {
            ColorType::Greyscale => 1,
            ColorType::Truecolor => 3,
            ColorType::Indexed => 1,
            ColorType::GreyscaleWithAlpha => 2,
            ColorType::TruecolorWithAlpha => 4,
        }
    }
}
