use crate::options::{Compression, PreCheckResult};
use crate::{options, profile_scope, LogLevel, LogMessage};
use byteorder::{BigEndian, WriteBytesExt};
use libdeflater::{crc32, CompressionLvl};
use std::io::{Error, Write, Read};
use tokio::sync::mpsc::UnboundedSender;
use zopfli::{Options, ZlibEncoder};
use flate2::read::DeflateDecoder;

/// [PNG Specification, version 3.0](https://www.w3.org/TR/png-3/)

/// Re-compresses deflate idat using zopfli with dynamic options
/// See [options::analyze](crate::options::analyze).
/// The input is only meant to be generated by oxipng as it does
/// not fully support the format but what oxipng generates.
pub fn rewrite_idat_with_zopfli(
    input: &[u8],
    compression: &Compression,
    logger: &UnboundedSender<LogMessage>,
) -> Vec<u8> {
    profile_scope!(std::any::type_name_of_val(&rewrite_idat_with_zopfli));
    const PNG_SIGNATURE: [u8; 8] = [137, 80, 78, 71, 13, 10, 26, 10];

    if input.len() < 8 || input[0..8] != PNG_SIGNATURE {
        return input.into();
    }

    let mut output = Vec::with_capacity(input.len());
    output.extend_from_slice(&PNG_SIGNATURE);

    let mut offset = 8;

    while offset < input.len() {
        if offset + 8 > input.len() {
            return input.into();
        }

        let length = u32::from_be_bytes([
            input[offset],
            input[offset + 1],
            input[offset + 2],
            input[offset + 3],
        ]) as usize;

        let chunk_type = &input[offset + 4..offset + 8];

        let chunk_end = offset + 8 + length;
        let crc_end = chunk_end + 4;
        if crc_end > input.len() {
            return input.into();
        }

        if chunk_type == b"IDAT" {
            let chunk_start = offset + 8;
            // See [zlib data format](https://en.wikipedia.org/wiki/Zlib#Data_format).
            // DICTID is not supported here, but it should never be used.
            let data = &input[
                chunk_start + 2 // removes the zlib header
                    ..
                    chunk_end - 4 // removes the zlib checksum
                ];
            let mut decoder = DeflateDecoder::new(data);

            let mut original_data = Vec::new();
            match decoder.read_to_end(&mut original_data) {
                Ok(original_size) => {
                    let data_size = data.len();
                    let bytes_saved = original_size.saturating_sub(data_size);
                    let savings_ratio = bytes_saved as f64 / original_size as f64;

                    match compression {
                        Compression::Normal => {
                            let result =
                                options::get_normal_precheck_result(savings_ratio, original_size);
                            compress_data_and_write_idat(input, logger, &mut output, original_data.as_slice(), offset, crc_end, data_size, result);
                        }
                        Compression::Best => {
                            let result =
                                options::get_best_pre_check_result(savings_ratio, original_size);
                            compress_data_and_write_idat(input, logger, &mut output, original_data.as_slice(), offset, crc_end, data_size, result);
                        }
                        compression => {
                            let _ = logger.send(LogMessage {
                                level: LogLevel::Error,
                                message: format!(
                                    "{} called with {:?}",
                                    std::any::type_name_of_val(&rewrite_idat_with_zopfli),
                                    compression
                                ),
                            });
                            return input.into();
                        }
                    }
                }
                Err(e) => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: format!("Failed to decompress PNG IDAT data: {:?}", e),
                    });
                    return input.into();
                }
            }
        } else {
            output.extend_from_slice(&input[offset..crc_end]);
        }

        offset = crc_end;
    }

    output
}

fn compress_data_and_write_idat(input: &[u8], logger: &UnboundedSender<LogMessage>, mut output: &mut Vec<u8>, original_data: &[u8], offset: usize, crc_end: usize, data_size: usize, result: PreCheckResult) {
    let out = match result {
        PreCheckResult::CompressWithZopfli(options) => {
            match compress(original_data, options) {
                Ok(out) => out,
                Err(e) => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: format!(
                            "Failed to compress PNG data with zopfli: {:?}",
                            e
                        ),
                    });
                    output.extend_from_slice(&input[offset..crc_end]);
                    return;
                }
            }
        },
        PreCheckResult::LibDeflater => {
            let mut compressor = libdeflater::Compressor::new(CompressionLvl::best());
            let mut out = vec![0u8; compressor.zlib_compress_bound(data_size)];
            let size = match compressor
                .zlib_compress(original_data, &mut out) {
                Ok(out) => out,
                Err(e) => {
                    let _ = logger.send(LogMessage {
                        level: LogLevel::Error,
                        message: format!(
                            "Failed to compress PNG data with libdeflate: {:?}",
                            e
                        ),
                    });
                    output.extend_from_slice(&input[offset..crc_end]);
                    return;
                }
            };
            out.truncate(size);
            out
        }
        PreCheckResult::Skip => {
            output.extend_from_slice(&input[offset..crc_end]);
            return;
        },
    };
    let out_size = out.len();
    if out_size > data_size + 6
    // Add 6 bytes for header and checksum
    {
        output.extend_from_slice(&input[offset..crc_end]);
        return;
    }
    match write_idat(&mut output, out_size, out) {
        Ok(_) => {}
        Err(e) => {
            let _ = logger.send(LogMessage {
                level: LogLevel::Error,
                message: format!(
                    "Failed to write PNG IDAT: {:?}",
                    e
                ),
            });
            output.extend_from_slice(&input[offset..crc_end]);
        }
    }
}

fn write_idat(output: &mut Vec<u8>, out_size: usize, data: Vec<u8>) -> std::io::Result<()> {
    output.write_u32::<BigEndian>(out_size as u32)?;
    output.extend_from_slice(b"IDAT");
    output.extend_from_slice(data.as_slice());
    output.write_u32::<BigEndian>(crc32(&output[output.len() - out_size - b"IDAT".len()..]))?;
    Ok(())
}

fn compress(original_data: &[u8], options: Options) -> Result<Vec<u8>, Error> {
    let mut encoder = ZlibEncoder::new(options, zopfli::BlockType::Dynamic, Vec::new())?;
    encoder.write_all(original_data)?;
    let out = encoder.finish()?;
    Ok(out)
}

#[macro_export]
macro_rules! compress {
    ($options:expr) => {{}};
}

#[macro_export]
macro_rules! stop {
    ($output:expr, $input:expr, $offset:expr) => {{
        input
    }};
}
