name: Build

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ "webassembly" ]
  pull_request:
    paths-ignore:
      - 'README.md'
    branches: [ "webassembly" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Web Assembly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-about,wasm-pack
      - name: Build
        run: |
          cd packobf
          wasm-pack build -t web
      - name: Prepare License
        run: cargo about generate about.hbs | perl -0777 -pe 's/\s+$/\n/' | tee -a LICENSE.md > /dev/null
      - name: Prepare CLI Executable
        # Always make sure files that are published contain the license files
        run: |
          mkdir dist
          cp packobf/pkg/* dist/
          cp LICENSE.md dist/
      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: JavaScript Package
          path: dist/*
